### ISSUE TITLE
Create only audit table by executing db/ahp-sql-create.php with mysql config

### ISSUE THREAD

**Issue by humbernieto** [bpmsg/ahp-os#1]
Hello, congratulations for your great work, I want to tell you that we want to use ahp-os to carry out research on the https://www.untrm.edu.pe/, but we have certain problems when trying to run the ahp-os software locally. Only the audit table is created when running db/ahp-sql-create.php. I would like to know with which versions or specific software I can run ahp-os. Thank you in advance, thank you very much.

humber.sanchez@untrm.edu.pe

**Comment by bpmsg** [comment]
I had to add . DBNAME . ".db" in ahp-sql-create.php and registration.php. Should work now. Please let me know.

**Comment by humbernieto** [comment]
Now it runs fine, but it still creates only the audit table in the db. maybe it is due to some software version, in my case I am using laragon in its latest version.
attached screenshots
![1](https://user-images.githubusercontent.com/56887259/152380480-1ae2a06a-eb4a-4e26-b32d-30fdbb777ed0.png)
![2](https://user-images.githubusercontent.com/56887259/152380494-e23ae574-b6ef-4693-9fd9-bc2e9739ab3b.png)
![3](https://user-images.githubusercontent.com/56887259/152380505-83275076-fbe3-498a-ae68-3144a3b8cb51.png)

**Comment by bpmsg** [comment]
What happens when you open ahp with  the web browser and try to register?
Did you try to run the priority calculator from the main page (does not use the database)?

**Comment by bpmsg** [comment]
Did you check php info?

**Comment by humbernieto** [comment]
What version of php does the ahp-os software work with?

**Comment by bpmsg** [comment]
I have it currently running with php 7.3.33, 7.2.24 and 7.4.9

**Comment by humbernieto** [comment]
Excellent, thank you very much, I will try.

**Comment by bpmsg** [comment]
I have installed laragon on my Windows PC and can reproduce the problem. Will see whether I find the cause.

**Comment by bpmsg** [comment]
After some testing I found the cause of the problem is that laragon uses mysql and not MariaDB (though it shows a mariadb.dll).
I tried sqlite, then the problem is that the PHP drivers are not enabled. If you find a way to enable them, it should work with sqlite. phpinfo() should show PDO drivers mysql, sqlite as shown attached.
The reason for not generating the tables are the default values given in the SQL statements,  for example "user_registration_datetime datetime NOT NULL DEFAULT '0000-00-00 00:00:00'". It seems, mysql cannot handle them in this form. When I take them out, I managed to register as user, but a lot of other SQL problems appear.
Solution: Try either to use/enable MariaDB instead of mysql, or use sqlite3 with PDO drivers enabled in PHP.
![Screenshot from 2022-02-04 15-34-30](https://user-images.githubusercontent.com/98625108/152492164-d6b59e43-5019-4aa2-b8d9-50de385e0c40.png)

**Comment by humbernieto** [comment]
I am very grateful, after many attempts I have managed to start ahp-os locally, installing MariaDB 10.2.41 in laragon, removing line 63 MY_DOMAIN from config.php. and adding "localhost:3306" on the same line.

Now I only have small details with the Email and Captcha, attached file, but nothing that cannot be solved by deactivating them or confirming the registration in the DB.
![captcha](https://user-images.githubusercontent.com/56887259/152587166-00720681-6420-4524-ad2e-b02f499d59ab.png)
![email](https://user-images.githubusercontent.com/56887259/152587182-2cd9c8a1-ca30-439a-bb76-bd5685c468d7.png)
![dbactiveuser](https://user-images.githubusercontent.com/56887259/152587194-2480ba1c-7fda-4202-ac5f-a870f3c5e432.png)

a thousand apologies if the translation is not very good

**Comment by bpmsg** [comment]
Congratulations. Yes, I have updated config-sample.php yesterday. Email should work, when you set your mail parameters correctly, CAPTCHA can be switched off. Enjoy the program. Translation is fine.

**Comment by humbernieto** [comment]
THANK YOU VERY MUCH, A BIG HUG
